name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Build and Upload Artifacts
      run: |
        pip install build
        python -m build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        path: dist/*
        name: dist
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Connect to EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy dist files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          source: dist/*
          target: /home/ubuntu/
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          private_key: ${{ secrets.EC2_SSH_KEY }}
