name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install pytest
      run: pip install pytest

    - name: Run tests
      run: python -m pytest
  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Build package
      if: contains(matrix.pyproject, 'pyproject.toml')
      run: |
        pip install build && python -m build

    #   # If only setup.py exists, use this:
    # - name: Build package
    #   if: !contains(matrix.pyproject, 'pyproject.toml')
    #   run: |
    #     pip install wheel && python setup.py sdist bdist_wheel

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist/
