name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    if: ${{ steps.test_conditions.outputs.should_run_tests }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies for testing
        run: |
          [ -f "requirements.txt" ] && pip install -r requirements.txt

      - name: Run Tests Without Framework
        run: |
          if [ -d "tests" ]; then
            echo "Running Tests..."
            python -m unittest discover -s tests
          else
            echo "No test folder found"
            exit 0;

      - name: Upload Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/
