name: Test and Build
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check for tests and run
        run: |
          pip install pytest requests
          if [ -d "tests" ]; then
            echo "Tests directory exists. Running tests..."
            pip install pytest  # Use pytest for testing
            python -m pytest tests/
          else
            echo "No tests directory found. Skipping tests."
          fi
