name: Test and Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Check for build configuration and build
        run: |
          if [ -f "pyproject.toml" ] || [ -f "setup.py" ]; then
            echo "Build configuration found. Executing build..."
            pip install build
            python -m build
            [ -d "dist" ] && echo "Build directory created. Build successful."
          else
            echo "No build configuration file found. Skipping build."
          fi
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
