name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    uses: actions/setup-python@v4
    with:
      python-version: '3.8'
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python -m pytest
