name: Build Python Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build package
        run: |
          if [[ -f setup.py ]]; then
            python setup.py sdist bdist_wheel
          elif [[ -f pyproject.toml ]]; then
            poetry build
          else
            echo "Warning: No build tool (setup.py or pyproject.toml) found. Skipping build."
          fi
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/
