name: Python Build (setup.py)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Upgrade pip and install build tools
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
    - name: Build with setup.py
      run: |
        python setup.py sdist bdist_wheel
    - uses: actions/upload-artifact@v4
      with:
        name: python-dist
        path: dist/
