name: Python Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Build artifacts
      run: |
        mkdir -p artifacts
        cp *.py artifacts/ || true
        cp *.txt artifacts/ || true
        cp *.cfg artifacts/ || true
        cp *.toml artifacts/ || true 
        zip -r artifacts.zip artifacts/
    - uses: actions/upload-artifact@v4
      with:
        name: artifact-build
        path: artifacts.zip
