name: Build Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Build Package
        run: |
          if [[ -f pyproject.toml ]]; then
            python -m build
          else
            pip install wheel
            python setup.py sdist bdist_wheel
          fi
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
