name: Build Artifacts

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Adjust to your project's Python version

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Build artifacts
      run: |
        if [ -f setup.py ]; then  python setup.py sdist bdist_wheel; fi
        if [ -f pyproject.toml ]; then pip install build && python -m build; fi
        if [ -f Dockerfile ]; then docker build -t repo-image . ; fi
        if [ ! -f setup.py ] && [ ! -f pyproject.toml ] && [ ! -f Dockerfile ]; then
          mkdir -p artifacts
          cp *.py *.txt *.toml 2>/dev/null || true
          zip -r artifacts.zip artifacts/
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts  # Update if needed
        path: artifacts  # Update if needed
