name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout artifacts
        uses: actions/checkout@v4

      - name: SSH to EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOSTNAME }}
          user: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Update dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip git python-dev
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pull latest code
        run: git pull origin main
      - name: Restart service
        run:  service_restart
      - name: Reload Nginx (Optional)
        run: |
          sudo systemctl reload nginx
