name: Python Build (Poetry)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Build with Poetry
      run: |
        poetry build
    - uses: actions/upload-artifact@v4
      with:
        name: poetry-build
        path: dist/

