name: Pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        if [[ -f requirements.txt ]]; then
          pip install -r requirements.txt
        fi
    - name: Install pytest
      run: pip install pytest
    - name: Run tests
      run: python -m pytest /tests
