name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: python -m pytest
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install build tools
        run: |
          python -m pip install build
      - name: Build artifacts
        run: python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
