name: Python Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
    - name: Install build tools
      run: pip install build wheel
    - name: Build Project
      run: |
        python -m build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
