name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check EC2 connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "ec2-13-233-110-40.ap-south-1.compute.amazonaws.com"
          username: "ubuntu"
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "✅ EC2 connection successful"
