name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check EC2 connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "13.233.110.40"
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "✅ EC2 connection successful"
